spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:siaes}
    username: ${DB_USERNAME:siaes}
    password: ${DB_PASSWORD:siaes}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:5}
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
      leak-detection-threshold: ${DB_POOL_MIN_IDLE:20}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_param

siaes:
  security:
    jwt:
      secret: ${JWT_SECRET:dev-only-insecure-secret-key-please-change-0123456789}
      access-expiration-days: ${SIAES_AUTH_TOKEN_EXPIRATION:365}
      refresh-expiration-hours: ${SIAES_AUTH_TOKEN_REFRESH_EXPIRATION:1}

management:
  datadog:
    metrics:
      export:
        enabled: ${DATADOG_ENABLED:false}